# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TU2jqMuACkkst6nyUENS8mcz0xlcEFix
"""

import pandas as pd
import joblib

class LoanModelInference:
    def __init__(self, model_path="loan_model.pkl"):
        self.model = joblib.load(model_path)
        self.feature_cols = self.model.feature_names_in_  # ambil fitur dari model yg udah fit

    def preprocess_input(self, input_data):
        df = pd.DataFrame([input_data])

        # Convert Yes/No
        if 'previous_loan_defaults_on_file' in df.columns:
            df['previous_loan_defaults_on_file'] = df['previous_loan_defaults_on_file'].map({'Yes': 1, 'No': 0})

        # One-hot encode categorical
        categorical_cols = ['person_gender', 'person_education', 'person_home_ownership', 'loan_intent']
        for col in categorical_cols:
            if col in df.columns:
                df[col] = df[col].astype(str)

        df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

        # Tambahkan kolom yang hilang dan urutkan sesuai model
        for col in self.feature_cols:
            if col not in df.columns:
                df[col] = 0
        df = df[self.feature_cols]
        return df

    def predict(self, input_data):
        df = self.preprocess_input(input_data)
        result = self.model.predict(df)[0]
        return int(result)

if __name__ == "__main__":
    sample_input = {
        'person_age': 28,
        'person_gender': 'female',
        'person_education': 'Bachelor',
        'person_income': 40000,
        'person_emp_exp': 2,
        'person_home_ownership': 'RENT',
        'loan_amnt': 5000,
        'loan_intent': 'MEDICAL',
        'loan_int_rate': 13.2,
        'loan_percent_income': 0.13,
        'cb_person_cred_hist_length': 3,
        'credit_score': 690,
        'previous_loan_defaults_on_file': 'No'
    }

    model = LoanModelInference()
    prediction = model.predict(sample_input)
    print(f"Hasil prediksi loan_status: {prediction} (1 = disetujui, 0 = ditolak)")

